### PR TITLE
Slim down module manager

### PR DESCRIPTION
**Pull request by muff1nman**
Okay, so I would like to move to executing modules in their own process.  The first step to doing this, I believe, is to slim down Module Manage and separate out some of its responsibilities into other classes.  The biggest change in this department then is the newly added ModuleExecutors, which do just that.. Execute Modules.  I also put the main method for the Module Manager into another class because it seems like it was cluttering up Module Manager with code relevant to module managing (such as parsing cmd line args).  Finally, to make development possible without a kinect, I have separated out the tests that fail do to the kinect being unavailable into new test files so that we can easily skip these tests with maven.  To do this use the -Dnokinect=true (will need to be documented).

### CODE REVIEW

**Comment by muff1nman** [comment]
Does anyone have a kinect to test this with?  I am nearly 90 percent sure that it should not affect anything kinect related but wanted to be sure

I wish I would have borrowed one of acmx's before hand haha

**Comment by muff1nman** [comment]
With c514620 I have decided that even then there is too much knowledge passed off to the executor it does not need to know about.  Before we where loading a module based off the ModuleMetaData, but really all it needs to know is its fully qualified class name and the jar file path.  I made it the ModuleManagers responsibility to gather this information from a Module's MetaData and pass it off to the executor.  

The beauty of this is that hopefully it will allow a single module to be run, even without the ModuleManager.  This will hopefully make it easier to create a ModuleProcessExecutor.  Also note that I changed the name on the ModuleThreadExecutor to ModuleSimpleExecutor.  This is because the original name was misleading as there is not any new thread creation ~ only if the Module itself creates a new thread (such as with the Processing Modules).  With that said it may make sense to actually create a ModuleThreadExecutor later down the road if we ever needed to run modules simultaneously (without having to rely on the non-present ModuleProcessExecutor)

**Comment by muff1nman** [comment]
Anyone else care to spot check me on this new code, before it gets merged into dev?

**Comment by adiviness** [comment]
If I had Internet.

**Pull request merged**
